### ISSUE TITLE
webrecorder desktop not really open after upgrade to catalina

### ISSUE THREAD

**Issue by slywiesner** [webrecorder/webrecorder-desktop#38]
upgraded laptop to catalina. uninstalled webrecorder. re-downloaded dmg and re-installed. rec'd error from apple security but said open anyway, and open. WR icon appears in dock, but never opens desktop app. double click doesn't work. ctrl/click/open doesn't either. ?

**Comment by Super10veBug** [comment]
I had this issue as well and was able to get a step further, opening the program. However, once open, the main page reads "There's been an error: No such page or content is not accessible"

Has there been any movement on this?

**Comment by Super10veBug** [comment]
I found the culprit in my case:

I had downloaded from the .dmg link on the README.md on thie page: https://github.com/webrecorder/webrecorder-desktop, and that link is for version 2.0.0., so that .dmg links to the old version.

When I downloaded from this page, https://github.com/webrecorder/webrecorder-desktop/releases/tag/v2.0.1   I got the correct version and am currently running it with no problem. I still received the security error from Apple, but the program is running fine.
